export const BATTLE_SELECT = {
    START_SELECT: 'START_SELECT',
    MOUSE_IN_SELECT: 'MOUSE_IN_SELECT',
    CONFIRM_SELECT: 'CONFIRM_SELECT',
    END_SELECT: 'END_SELECT'
}


export const ANIMATION_TYPE = {
    ATTACK_ANIMATION: 'ATTACK_ANIMATION',
    AIM_ANIMATION: 'AIM_ANIMATION',
}