const EFFECT_TYPE_SINGLE = 'EFFECT_TYPE_SINGLE'		
const EFFECT_TYPE_FIELD = 'EFFECT_TYPE_FIELD'
const EFFECT_TYPE_EQUIP = 'EFFECT_TYPE_EQUIP'		
const EFFECT_TYPE_ACTIONS = 'EFFECT_TYPE_ACTIONS'	
const EFFECT_TYPE_ACTIVATE = 'EFFECT_TYPE_ACTIVATE'	
const EFFECT_TYPE_FLIP = 'EFFECT_TYPE_FLIP'	
const EFFECT_TYPE_IGNITION = 'EFFECT_TYPE_IGNITION'	
const EFFECT_TYPE_TRIGGER_O	= 'EFFECT_TYPE_TRIGGER_O'
const EFFECT_TYPE_QUICK_O = 'EFFECT_TYPE_QUICK_O'		
const EFFECT_TYPE_TRIGGER_F	= 'EFFECT_TYPE_TRIGGER_F'	
const EFFECT_TYPE_QUICK_F = 'EFFECT_TYPE_QUICK_F'		
const EFFECT_TYPE_CONTINUOUS = 'EFFECT_TYPE_CONTINUOUS'		
const EFFECT_TYPE_XMATERIAL	= 'EFFECT_TYPE_XMATERIAL'	
const EFFECT_TYPE_GRANT	= 'EFFECT_TYPE_GRANT'		
const EFFECT_TYPE_TARGET = 'EFFECT_TYPE_TARGET'

export default {
    EFFECT_TYPE_SINGLE,
    EFFECT_TYPE_FIELD,
    EFFECT_TYPE_EQUIP,
    EFFECT_TYPE_ACTIONS,
    EFFECT_TYPE_ACTIVATE,
    EFFECT_TYPE_FLIP,
    EFFECT_TYPE_IGNITION,
    EFFECT_TYPE_TRIGGER_O,
    EFFECT_TYPE_QUICK_O,
    EFFECT_TYPE_TRIGGER_F,
    EFFECT_TYPE_QUICK_F,
    EFFECT_TYPE_CONTINUOUS,
    EFFECT_TYPE_XMATERIAL,
    EFFECT_TYPE_GRANT,
    EFFECT_TYPE_TARGET
}